# -*- coding: utf-8 -*-
"""Suma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ART2DKi6J9hlqgSawgCH1JkjiMNRJnFb
"""

#Issue numero 4 - suma - Horacio
def suma(x,y):
    return x+y